import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

// const geistSans = localFont({
//     src: './fonts/GeistVF.woff',
//     variable: '--font-geist-sans',
//     weight: '100 900'
// });
// const geistMono = localFont({
//     src: './fonts/GeistMonoVF.woff',
//     variable: '--font-geist-mono',
//     weight: '100 900'
// });

export const metadata: Metadata = {
    title: '🐸next-js-playground🐸',
    description: 'Generated by create next app'
};

// 정적 메타데이터
// export const metadata = {
//     title: '제목!',
//     description: '설명..',
//     openGraph: {
//         title: '제목'
//         // ...
//     },
//     twitter: {
//         title: '제목'
//         // ...
//     }
// };

// 동적 경로에서 메타데이터를 생성하려면,
// generateMetadata 함수를 사용

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
            // className={`${geistSans.variable} ${geistMono.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
